config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  devise_for :users, skip: [:registrations]

  root to: "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :patient_exercises, only: [:index, :show, :new, :create] do
    member do
      patch 'success'
      patch 'deduct_success'
      patch 'failed'
      patch 'deduct_failed'
      patch 'help'
      patch 'deduct_help'
    end

    collection do
      get 'start_session', to: 'patient_exercises#start_session'
      get 'select_exercises', to: 'patient_exercises#select_exercises'
    end
  end

  get 'backoffice', to: 'backoffice#index'

  resources :exercises, only: [:index, :new, :create]
  resources :patients, only: [:index, :new, :create]
  resources :therapists, only: [:index, :new, :create]
end

app/controllers/patient_exercises_controller.rb
class PatientExercisesController < ApplicationController
  def index
    @patient_exercises = PatientExercise.available_exercises
  end

  def show
    @patient_id = params[:id]
    @patient_exercises = PatientExercise.where(patient_id: params[:id]).order(:id)
  end

  def new
    @patient_id = params[:patient_id]
    @available_exercises = Exercise.available_exercises(params[:patient_id])
    @patient_exercise = PatientExercise.new
  end

  def create
    patient_id = params[:patient_id]
    exercise_ids = params[:exercise_ids]

    begin
      ActiveRecord::Base.transaction do
        exercise_ids.each do |id|
          PatientExercise.create!(patient_id: patient_id, exercise_id: id)
        end
      end

      redirect_to patient_exercise_path(patient_id), notice: "Exercises successfully assigned to patient."

    rescue ActiveRecord::RecordInvalid => e
      redirect_to new_patient_exercise_path(patient_id: patient_id), alert: "Failed to assign exercises: #{e.message}"
    end
  end

  def select_exercises
    patient_id = params[:patient_id]
    @patient_exercises = PatientExercise.where(patient_id: patient_id).order(:id)

    @therapists = Therapist.all
  end

  def start_session
    if params[:patient_exercise_ids].nil?
      flash[:message] = 'Selecione ao menos um exercício para iniciar a avaliação.'
      redirect_back(fallback_location: root_path)
    end
    @patient_exercises = PatientExercise.where(id: params[:patient_exercise_ids]).order(:id)
  end

  def success
    patient_exercise = PatientExercise.find(params[:id])
    patient_exercise.update(success: patient_exercise.success + 1)
    patient_exercise.update(attempts: patient_exercise.attempts + 1)

    redirect_to start_session_patient_exercises_path(patient_exercise_ids: params[:patient_exercise_ids])
  end

  def deduct_success
    patient_exercise = PatientExercise.find(params[:id])
    patient_exercise.update(success: patient_exercise.success - 1)
    patient_exercise.update(attempts: patient_exercise.attempts - 1)

    redirect_to start_session_patient_exercises_path(patient_exercise_ids: params[:patient_exercise_ids])
  end

  def failed
    patient_exercise = PatientExercise.find(params[:id])
    patient_exercise.update(failed: patient_exercise.failed + 1)
    patient_exercise.update(attempts: patient_exercise.attempts + 1)

    redirect_to start_session_patient_exercises_path(patient_exercise_ids: params[:patient_exercise_ids])
  end

  def deduct_failed
    patient_exercise = PatientExercise.find(params[:id])
    patient_exercise.update(failed: patient_exercise.failed - 1)
    patient_exercise.update(attempts: patient_exercise.attempts - 1)

    redirect_to start_session_patient_exercises_path(patient_exercise_ids: params[:patient_exercise_ids])
  end

  def help
    patient_exercise = PatientExercise.find(params[:id])
    patient_exercise.update(help: patient_exercise.help + 1)
    patient_exercise.update(attempts: patient_exercise.attempts + 1)

    redirect_to start_session_patient_exercises_path(patient_exercise_ids: params[:patient_exercise_ids])
  end

  def deduct_help
    patient_exercise = PatientExercise.find(params[:id])
    patient_exercise.update(help: patient_exercise.help - 1)
    patient_exercise.update(attempts: patient_exercise.attempts - 1)

    redirect_to start_session_patient_exercises_path(patient_exercise_ids: params[:patient_exercise_ids])
  end

  private

  def patient_exercise_params
    params.permit(:patient_id, :exercise_id)
  end
end

app/views/patient_exercises/index.html.erb
<%= link_to 'Voltar', backoffice_path %>

<h1>Exercícios do </h1>

<% @patients.each do |patient| %>
  <% if patient.patient_exercises.any? %>
    <p> <%= link_to "#{patient.name}", new_patient_exercise_path(patient_id: patient.id) %> </p>
  <% end %>
<% end %>

app/views/patient_exercises/new.html.erb
<%= link_to 'Voltar', patients_path %>
<% if @available_exercises.present? %>
  <h1>Selecione os treinos que deseja adicionar</h1>

  <%= form_with url: patient_exercises_path(patient_id: @patient_id), method: :post do %>
    <ul>
      <% @available_exercises.each do |exercise| %>
        <li>
          <%= check_box_tag 'exercise_ids[]', exercise.id %>
          <%= label_tag "exercise_ids_#{exercise.id}", exercise.name %>
        </li>
      <% end %>
    </ul>

    <%= submit_tag 'Adicionar Treinos' %>
  <% end %>
<% else %>
  <h1>Não há treinos disponíveis para esse paciente<h1>
<% end %>

app/views/patient_exercises/select_exercises.html.erb
<p><%= link_to 'Voltar', patients_path %></p>

<%= form_with url: start_session_patient_exercises_path(patient_id: @patient_exercises.first.patient.id), method: :get, data: { turbo: false } do %>
  <table>
    <thead>
      <tr>
        <th>Treino</th>
        <th>Sucessos</th>
        <th>Falhas</th>
        <th>Com ajuda</th>
        <th>Tentativas</th>
      </tr>
    </thead>
    <tbody>
      <% @patient_exercises.each do |patient_exercise| %>
        <tr>
          <td>
            <%= check_box_tag "patient_exercise_ids[]", patient_exercise.id %>
            <%= patient_exercise.exercise.name %>
          </td>
          <td><%= patient_exercise.success %></td>
          <td><%= patient_exercise.failed %></td>
          <td><%= patient_exercise.help %></td>
          <td><%= total_attempts(patient_exercise) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="field">
    <h3><%= label_tag 'Terapeuta' %></h3>
    <%= select_tag :therapist_name, options_for_select(@therapists.map { |therapist| [therapist.name, therapist.id] }) %>
  </div>
  <p><%= submit_tag "Iniciar Avaliação" %></p>
<% end %>

app/views/patient_exercises/show.html.erb
<%= flash[:message] %>
<%= link_to 'Voltar', patients_path %>

<h1>Lista de Treinos - <%= @patient_exercises.first.patient.name %></h1>

<% if admin_signed_in? %>
  <tbody>
    <% @patient_exercises.each do |patient_exercise| %>
      <tr>
        <td>
          <p><%= patient_exercise.exercise.name %></p>
        </td>
      </tr>
    <% end %>
  </tbody>

  <%= link_to "Adicionar Treinos", new_patient_exercise_path(patient_id: @patient_id) %>
<% end %>

app/views/patient_exercises/start_session.html.erb
<h1>Avaliação <%= @patient_exercises.first.patient.name %> - <%= @patient_exercises.first.created_at.strftime("%d/%m/%Y") %> </h1>
<h2>Terapeuta: <%= @patient_exercises.first.therapist.name %></h1>

<% @patient_exercises.each do |patient_exercise| %>
  <h3> <%= "#{patient_exercise.exercise.name} - Tentativas: #{patient_exercise.attempts}" %> </h3>
  <p>Sucesso: <%= patient_exercise.success %> <p>
  <p>
    <%= link_to '+', success_patient_exercise_path(patient_exercise, patient_exercise_ids: patient_exercise_ids(@patient_exercises)), data: { "turbo-method": :patch } %>
    <%= link_to '-', deduct_success_patient_exercise_path(patient_exercise, patient_exercise_ids: patient_exercise_ids(@patient_exercises)), data: { "turbo-method": :patch } %>
  </p>
  <p>Falha: <%= patient_exercise.failed %> <p>
  <p>
    <%= link_to '+', failed_patient_exercise_path(patient_exercise, patient_exercise_ids: patient_exercise_ids(@patient_exercises)), data: { "turbo-method": :patch } %>
    <%= link_to '-', deduct_failed_patient_exercise_path(patient_exercise, patient_exercise_ids: patient_exercise_ids(@patient_exercises)), data: { "turbo-method": :patch } %>
  </p>
  <p>Com ajuda: <%= patient_exercise.help %> <p>
  <p>
    <%= link_to '+', help_patient_exercise_path(patient_exercise, patient_exercise_ids: patient_exercise_ids(@patient_exercises)), data: { "turbo-method": :patch } %>
    <%= link_to '-', deduct_help_patient_exercise_path(patient_exercise, patient_exercise_ids: patient_exercise_ids(@patient_exercises)), data: { "turbo-method": :patch } %>
  </p>
<% end %>

<h2><%= link_to "Finalizar", patient_exercise_path(@patient_exercises.first.patient) %></h2>