config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  devise_for :users, skip: [:registrations]

  root to: "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :patient_exercises, only: [:index, :show, :new, :create] do
    member do
      patch 'success'
      patch 'deduct_success'
      patch 'failed'
      patch 'deduct_failed'
      patch 'help'
      patch 'deduct_help'
    end

    collection do
      get 'start_session', to: 'patient_exercises#start_session'
      get 'select_exercises', to: 'patient_exercises#select_exercises'
    end
  end

  get 'backoffice', to: 'backoffice#index'

  resources :exercises, only: [:index, :new, :create]
  resources :patients, only: [:index, :new, :create]
  resources :therapists, only: [:index, :new, :create]
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :patient_exercises
  has_many :exercises, through: :patient_exercises

  validates :name, presence: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user_or_admin!

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
    @exercises = Exercise.all
  end

  def create
    patient = Patient.new(name: patient_params[:name])
    exercise_ids = params[:exercise_ids]

    if patient.save
      begin
        ActiveRecord::Base.transaction do
          exercise_ids.each do |id|
            PatientExercise.create!(patient_id: patient.id, exercise_id: id)
          end
        end
        flash[:message] = 'Paciente criado com sucesso.'

        redirect_to patient_exercise_path(patient.id)

      rescue ActiveRecord::RecordInvalid => e
        redirect_to new_patient_path(patient_id: patient_id), alert: "Failed to assign exercises: #{e.message}"
      end
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :exercise_id)
  end

  def authenticate_user_or_admin!
    if user_signed_in?
      return true
    elsif admin_signed_in?
      return true
    else
      redirect_to new_user_session_path, alert: 'You need to sign in first.'
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/index.html.erb
<%= link_to 'Voltar', backoffice_path %>

<h1>Lista de pacientes - <%= admin_signed_in? ? "Admin" : "Terapeuta" %> </h1>

<% @patients.each do |patient| %>
  <% if patient.patient_exercises.any? %>
    <p> <%= link_to "#{patient.name}", admin_signed_in? ? patient_exercise_path(patient) : select_exercises_patient_exercises_path(patient_id: patient.id) %> </p>
  <% end %>
<% end %>

app/views/patients/new.html.erb
<%= link_to 'Voltar', backoffice_path %>
<h1>Cadastrar paciente</h1>

<div>
  <%= flash[:message] %>
</div>

<%= form_with(model: @patient, local: true) do |form| %>
  <div class="field">
    <%= form.label 'Nome' %>
    <%= form.text_field :name %>
  </div>

  <h1>Selecione os treinos que deseja adicionar</h1>

  <ul>
    <% @exercises.each do |exercise| %>
      <li>
        <%= check_box_tag 'exercise_ids[]', exercise.id %>
        <%= label_tag "exercise_ids_#{exercise.id}", exercise.name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= submit_tag 'Criar Paciente' %>
  </div>
<% end %>